// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPvStB7D8Nu3nJPXo2sPYzaA6MEIj2GaE',
    appId: '1:677935756880:web:696ced276410a7af8ec355',
    messagingSenderId: '677935756880',
    projectId: 'udemy-app-b848c',
    authDomain: 'udemy-app-b848c.firebaseapp.com',
    storageBucket: 'udemy-app-b848c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDi3nmEeXPi3B6bcfhKdgpKhJpXwxFK3dc',
    appId: '1:677935756880:android:06a9207ab6fb25468ec355',
    messagingSenderId: '677935756880',
    projectId: 'udemy-app-b848c',
    storageBucket: 'udemy-app-b848c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBn3m8qHyY_oTvc7svJUt1GDvHJ7453-vc',
    appId: '1:677935756880:ios:1b09079b49e639e58ec355',
    messagingSenderId: '677935756880',
    projectId: 'udemy-app-b848c',
    storageBucket: 'udemy-app-b848c.appspot.com',
    iosBundleId: 'com.example.udemyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBn3m8qHyY_oTvc7svJUt1GDvHJ7453-vc',
    appId: '1:677935756880:ios:b1123919a2d7fb0a8ec355',
    messagingSenderId: '677935756880',
    projectId: 'udemy-app-b848c',
    storageBucket: 'udemy-app-b848c.appspot.com',
    iosBundleId: 'com.example.udemyApp.RunnerTests',
  );
}
